### ISSUE TITLE
Allow placing fences on paths

### ISSUE THREAD

**Issue by ardissaps** [Steveplays28/pathunderfencegates#1]
Look like vanilla already did for gates, but not fence.

**Comment by Steveplays28** [comment]
I could do that but then the fence will float slightly above the dirt path, because the dirt path is actually slightly lower than normal blocks

**Comment by ardissaps** [comment]
Look like a little bit elevated dirt path when only under fence is ok.

**Comment by Steveplays28** [comment]
I will see if I can/want to make this. I'll reply back later.

**Comment by ardissaps** [comment]
No hurry, take your time. This is Sunday! :p

**Comment by Steveplays28** [comment]
True, thanks haha

**Comment by Psychodeus** [comment]
How was the progress gentleman?

**Comment by Steveplays28** [comment]
I haven't really gotten around to it yet, same with my 2 other mods.
I'm also busy with life things, so it might take a while. Feel free to fork and pr though.

**Comment by Steveplays28** [comment]
If I'm going to implement this, I want to make sure the pole of the fence/sign extends down to the path's surface, I don't like how it looks otherwise. This should be quite doable.

I did implement this for a few other blocks though (glass panes, bells, wall signs, and trapdoors), fixing [MC-84731](https://bugs.mojang.com/browse/MC-84731).

I'll see when I get around to implementing this.

**Comment by Steveplays28** [comment]
Honestly this is quite a bit out of scope for this mod. Might make a separate mod in the future for something like this though.
